---
title: "PA1"
author: "Sophie Song"
date: "10/16/2019"
output: 
  github_document:
    fig_width: 5
    fig_height: 5
    dev: jpeg
  
  
---

### Loading and preprocessing the data
```{r global_options, echo=T, results='hide', message=F, warning=F}
library(ggplot2)
library(dplyr)
library(plyr)
df <- read.csv("activity.csv") #read data
```

### Task1: What is mean total number of steps taken per day?
```{r}
#calculate the total number, the mean and the median of steps taken per day
df1 <- df %>% filter(df$steps != "NA") %>% group_by(date) %>% dplyr::summarise(sum_step=sum(steps),mean_step=mean(steps),median_step=median(steps))

# display the total number, the mean and the median of steps taken per day
df1 

#draw histogram
ggplot(df1,aes(x=sum_step))+geom_histogram(bins=20,fill="steelblue",color="white")+labs(title = "Histogram for the total No. of steps taken per  day")+theme(plot.title=element_text(hjust=0.5)) 


```

  
### Task2: What is the average daily activity pattern?
```{r}
#tidy the data
df2 <- df %>% filter(df$steps != "NA") %>% group_by(interval) %>% dplyr::summarise(mean_step = mean(steps)) 

#draw the graph
plot(mean_step~interval,data=df2,type="l") 

#Find Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps
df2[which.max(df2$mean_step),] 
```

  
### Task3: Imputing missing values
```{r}
df3 <- df

#calculate the total number of missing values
plyr::count(df[is.na(df$steps),]$steps) 

#filling in all of the missing values in the dataset with the mean for that 5-minute interval
for (i in 1:nrow(df3)) {
  if (is.na(df3$steps[i])){
    df3$steps[i] = df2$mean_step[which(df2$interval == df3$interval[i])]
  } 
}

#Create a new dataset that is equal to the original dataset but with the missing data filled in.
head(df3)

#Calculate the mean and median total number of steps taken per day
df4 <- df3 %>% group_by(date) %>% dplyr::summarise(sum_step=sum(steps),mean_step=mean(steps),median_step=median(steps))

#report the mean and median total number of steps taken per day
df4

#draw histogram. Imputing missing data on the estimates of the total daily number of steps changes the shape of the graph
ggplot(df4,aes(x=sum_step))+geom_histogram(bins=20,fill="steelblue",color="white")+labs(title = "Histogram for the total No. of steps taken per  day")+theme(plot.title=element_text(hjust=0.5))

```

  
### Task 4: Are there differences in activity patterns between weekdays and weekends?
```{r}
#Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
df5 <- df3
df5$date <- as.Date(df5$date)
df5$week <- weekdays(df5$date)
df5$weekends_or_not <- ifelse(df5$week %in% c("Sunday","Saturday"),"weekend","weekday")

#calculate the average number of steps taken, averaged across all weekday days or weekend days
df6 <- df5 %>% group_by(interval,weekends_or_not) %>% dplyr::summarise(mean_step=mean(steps))

#Make the panel plot
ggplot(df6,aes(x=interval,y=mean_step))+geom_line()+facet_grid(weekends_or_not~.)
```

